name: display
#on: [push, workflow_dispatch]
on: 
    - workflow_dispatch
    - push
    
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        # run: |
        #   echo "Cloning the repo"
        #   echo "${{ toJson(github.repository) }}"
        #   git clone https://github.com/${{ github.repository }}.git
        uses: actions/checkout@v6
      - name: Install Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Display Node version
        run: node -v
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
        